var express = require("express");
var bodyParser = require("body-parser");
var path = require("path"); 
var app = express();
var PORT = process.env.PORT || 3000; 
var friends = require("./app/data/friends");
var apiRoutes = require("./app/routing/apiRoutes");
var htmlRoutes = require("./app/routing/htmlRoutes");
app.use(bodyParser.urlencoded({extended: false}));   
app.use(bodyParser.json());